"""initial schema

Revision ID: 31def5154bc5
Revises: 
Create Date: 2026-09-16 22:18:21.315684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31def5154bc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('email', name=op.f('uq_clients_email'))
    )
    op.create_table('studio_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_users')),
    sa.UniqueConstraint('email', name=op.f('uq_studio_users_email'))
    )
    op.create_table('magic_links',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_magic_links_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_links'))
    )
    op.create_index(op.f('ix_magic_links_client_id'), 'magic_links', ['client_id'], unique=False)
    op.create_index(op.f('ix_magic_links_token_hash'), 'magic_links', ['token_hash'], unique=False)
    op.create_table('shoots',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('shoot_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'uploading', 'culling', 'culled', 'published', 'selects_done', 'delivered', name='shoot_status'), server_default='draft', nullable=False),
    sa.Column('select_limit', sa.Integer(), nullable=True),
    sa.Column('downloads_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_shoots_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shoots'))
    )
    op.create_index(op.f('ix_shoots_client_id'), 'shoots', ['client_id'], unique=False)
    op.create_table('images',
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_key', sa.String(length=500), nullable=False),
    sa.Column('web_key', sa.String(length=500), nullable=True),
    sa.Column('thumb_key', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blur_variance', sa.Float(), nullable=True),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('eyes_closed', sa.Boolean(), nullable=True),
    sa.Column('ai_verdict', sa.Enum('keep', 'reject', name='verdict'), nullable=True),
    sa.Column('ai_reasons', postgresql.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('admin_verdict', sa.Enum('keep', 'reject', name='verdict'), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('in_gallery', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gallery_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], name=op.f('fk_images_shoot_id_shoots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_index('ix_images_shoot_id', 'images', ['shoot_id'], unique=False)
    op.create_index('ix_images_shoot_id_ai_verdict', 'images', ['shoot_id', 'ai_verdict'], unique=False)
    op.create_index('ix_images_shoot_id_in_gallery', 'images', ['shoot_id', 'in_gallery'], unique=False)
    op.create_table('jobs',
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('cull', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='job_status'), server_default='queued', nullable=False),
    sa.Column('progress_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], name=op.f('fk_jobs_shoot_id_shoots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_shoot_id'), 'jobs', ['shoot_id'], unique=False)
    op.create_table('edit_requests',
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'rejected', name='edit_status'), server_default='open', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_edit_requests_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_edit_requests_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], name=op.f('fk_edit_requests_shoot_id_shoots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edit_requests'))
    )
    op.create_index(op.f('ix_edit_requests_shoot_id'), 'edit_requests', ['shoot_id'], unique=False)
    op.create_table('finals',
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_finals_image_id_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], name=op.f('fk_finals_shoot_id_shoots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finals'))
    )
    op.create_index(op.f('ix_finals_shoot_id'), 'finals', ['shoot_id'], unique=False)
    op.create_table('selects',
    sa.Column('shoot_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_selects_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_selects_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shoot_id'], ['shoots.id'], name=op.f('fk_selects_shoot_id_shoots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selects')),
    sa.UniqueConstraint('image_id', 'client_id', name='uq_selects_image_client')
    )
    # ### end Alembic commands ###
    op.create_foreign_key(
        'fk_shoots_cover_image_id',
        'shoots', 'images',
        ['cover_image_id'], ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shoots_cover_image_id', 'shoots', type_='foreignkey')
    op.drop_table('selects')
    op.drop_index(op.f('ix_finals_shoot_id'), table_name='finals')
    op.drop_table('finals')
    op.drop_index(op.f('ix_edit_requests_shoot_id'), table_name='edit_requests')
    op.drop_table('edit_requests')
    op.drop_index(op.f('ix_jobs_shoot_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_images_shoot_id_in_gallery', table_name='images')
    op.drop_index('ix_images_shoot_id_ai_verdict', table_name='images')
    op.drop_index('ix_images_shoot_id', table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_shoots_client_id'), table_name='shoots')
    op.drop_table('shoots')
    op.drop_index(op.f('ix_magic_links_token_hash'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_client_id'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_table('studio_users')
    op.drop_table('clients')
    # ### end Alembic commands ###
    for enum_name in ("edit_status", "job_status", "job_kind", "verdict", "shoot_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
