"""initial schema

Revision ID: b793dd612c10
Revises: 
Create Date: 2026-09-17 20:50:43.235328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b793dd612c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_members',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_committee_members'))
    )
    op.create_index(op.f('ix_committee_members_academic_year'), 'committee_members', ['academic_year'], unique=False)
    op.create_table('events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='event_status'), server_default='draft', nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('slug', name=op.f('uq_events_slug'))
    )
    op.create_index(op.f('ix_events_academic_year'), 'events', ['academic_year'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='user_role'), server_default='student', nullable=False),
    sa.Column('batch', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('photos',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumb_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_photos_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index(op.f('ix_photos_event_id'), 'photos', ['event_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('event-idea', 'coverage-request', 'design-request', 'workshop-request', 'collaboration', 'equipment', 'feedback', 'complaint', 'other', name='suggestion_category'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'reviewing', 'planned', 'declined', name='suggestion_status'), server_default='new', nullable=False),
    sa.Column('theme_id', sa.String(length=50), nullable=True),
    sa.Column('theme_label', sa.String(length=200), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_suggestions_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    op.create_index(op.f('ix_suggestions_author_id'), 'suggestions', ['author_id'], unique=False)
    op.create_index(op.f('ix_suggestions_theme_id'), 'suggestions', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_theme_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_author_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_photos_event_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_academic_year'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_committee_members_academic_year'), table_name='committee_members')
    op.drop_table('committee_members')
    # ### end Alembic commands ###
    for enum_name in ("suggestion_status", "suggestion_category", "event_status", "user_role"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
